version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3001:80"
    volumes:
      - ./backend/src:/app/src