version: '3.8'

services:
  front:
    build:
      context: front
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
  back:
    build:
      context: backend
      dockerfile: ./Dockerfile.prod
    ports:
      - "3001:80"